# Generated by Django 4.2.2 on 2023-08-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reg', models.TextField()),
                ('dept', models.TextField()),
                ('domain', models.CharField(choices=[('Robotics', 'Robotics'), ('Creatives', 'Creatives'), ('Content', 'Content')], max_length=20)),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('reason', models.TextField()),
            ],
        ),
    ]
